import jsPDF from 'jspdf';
import { Recipe } from '../types';

export function generateRecipeText(recipe: Recipe): string {
  const line = '='.repeat(60);
  const subLine = '-'.repeat(60);

  let text = `${line}\n`;
  text += `FLAVOR FUSION AI - SMART RECIPE ASSISTANT\n`;
  text += `${line}\n\n`;
  text += `RECIPE TITLE: ${recipe.title.toUpperCase()}\n`;
  text += `Cuisine: ${recipe.cuisine} | Difficulty: ${recipe.difficulty} | Servings: ${recipe.servingSize}\n`;
  text += `Prep Time: ${recipe.prepTimeMinutes} mins | Cook Time: ${recipe.cookTimeMinutes} mins | Total: ${recipe.totalTimeMinutes} mins\n\n`;
  text += `DESCRIPTION:\n${recipe.description}\n\n`;

  text += `${subLine}\nREQUIRED INGREDIENTS:\n${subLine}\n`;
  recipe.ingredients.forEach(ing => {
    text += `• ${ing}\n`;
  });

  if (recipe.missingIngredients && recipe.missingIngredients.length > 0) {
    text += `\n${subLine}\nMISSING / SUGGESTED PANTRY INGREDIENTS (MAX 3):\n${subLine}\n`;
    recipe.missingIngredients.forEach(ing => {
      text += `+ ${ing}\n`;
    });
    if (recipe.missingIngredientsMessage) {
      text += `Note: ${recipe.missingIngredientsMessage}\n`;
    }
  }

  text += `\n${subLine}\nNUTRITION INFORMATION (PER SERVING):\n${subLine}\n`;
  text += `• Calories: ${recipe.nutrition.calories} kcal\n`;
  text += `• Protein: ${recipe.nutrition.protein}\n`;
  text += `• Carbohydrates: ${recipe.nutrition.carbohydrates}\n`;
  text += `• Fat: ${recipe.nutrition.fat}\n`;
  text += `• Fiber: ${recipe.nutrition.fiber}\n`;
  text += `• Sugar: ${recipe.nutrition.sugar}\n`;

  text += `\n${subLine}\nSTEP-BY-STEP COOKING INSTRUCTION:\n${subLine}\n`;
  recipe.instructions.forEach(step => {
    text += `Step ${step.stepNumber} [${step.estimatedMinutes ? step.estimatedMinutes + ' mins' : 'Direct'}]:\n`;
    text += `${step.instruction}\n`;
    if (step.tip) {
      text += `  💡 Pro Tip: ${step.tip}\n`;
    }
    text += `\n`;
  });

  if (recipe.cookingTips && recipe.cookingTips.length > 0) {
    text += `${subLine}\nCHEF'S PRO TIPS:\n${subLine}\n`;
    recipe.cookingTips.forEach(tip => {
      text += `• ${tip}\n`;
    });
    text += `\n`;
  }

  if (recipe.healthierAlternatives && recipe.healthierAlternatives.length > 0) {
    text += `${subLine}\nHEALTHIER ALTERNATIVES & SWAPS:\n${subLine}\n`;
    recipe.healthierAlternatives.forEach(alt => {
      text += `• ${alt}\n`;
    });
    text += `\n`;
  }

  text += `${line}\nGenerated by Flavor Fusion AI – Smart AI Kitchen Assistant\n${line}\n`;
  return text;
}

export function downloadRecipeTxt(recipe: Recipe): void {
  const textContent = generateRecipeText(recipe);
  const blob = new Blob([textContent], { type: 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  const fileName = recipe.title.toLowerCase().replace(/[^a-z0-9]+/g, '_') + '_recipe.txt';
  link.download = fileName;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

export function downloadRecipePdf(recipe: Recipe): void {
  const doc = new jsPDF({
    orientation: 'p',
    unit: 'mm',
    format: 'a4'
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 15;
  let y = 20;

  // Header Banner
  doc.setFillColor(255, 138, 61); // Primary Tangerine
  doc.rect(0, 0, pageWidth, 18, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  doc.text('FLAVOR FUSION AI – SMART RECIPE ASSISTANT', margin, 12);

  y = 28;

  // Title
  doc.setTextColor(44, 44, 44);
  doc.setFont('times', 'bold');
  doc.setFontSize(20);
  const splitTitle = doc.splitTextToSize(recipe.title, pageWidth - (margin * 2));
  doc.text(splitTitle, margin, y);
  y += (splitTitle.length * 8) + 4;

  // Metadata Badges Line
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(102, 102, 102);
  const metaText = `Cuisine: ${recipe.cuisine}  |  Difficulty: ${recipe.difficulty}  |  Servings: ${recipe.servingSize}  |  Total Time: ${recipe.totalTimeMinutes} mins`;
  doc.text(metaText, margin, y);
  y += 8;

  // Description
  doc.setFontSize(10);
  doc.setTextColor(70, 70, 70);
  const splitDesc = doc.splitTextToSize(recipe.description, pageWidth - (margin * 2));
  doc.text(splitDesc, margin, y);
  y += (splitDesc.length * 5) + 8;

  // Helper function for page overflow check
  const checkPageOverflow = (neededHeight: number) => {
    if (y + neededHeight > pageHeight - margin) {
      doc.addPage();
      y = 20;
    }
  };

  // Ingredients Section
  checkPageOverflow(30);
  doc.setFillColor(244, 237, 228);
  doc.rect(margin, y, pageWidth - (margin * 2), 7, 'F');
  doc.setTextColor(44, 44, 44);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.text('INGREDIENTS AT HOME', margin + 4, y + 5);
  y += 12;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  recipe.ingredients.forEach(ing => {
    checkPageOverflow(6);
    doc.text(`• ${ing}`, margin + 4, y);
    y += 5;
  });
  y += 4;

  // Missing Ingredients
  if (recipe.missingIngredients && recipe.missingIngredients.length > 0) {
    checkPageOverflow(20);
    doc.setFillColor(255, 248, 242);
    doc.setDrawColor(255, 159, 67);
    doc.roundedRect(margin, y, pageWidth - (margin * 2), 16, 2, 2, 'FD');
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(230, 81, 0);
    doc.text('Missing Pantry Essentials (Max 3):', margin + 4, y + 5);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(60, 60, 60);
    doc.text(recipe.missingIngredients.join(', '), margin + 4, y + 11);
    y += 22;
  }

  // Nutrition Card
  checkPageOverflow(25);
  doc.setFillColor(245, 247, 242);
  doc.rect(margin, y, pageWidth - (margin * 2), 16, 'F');
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(111, 125, 87); // Olive green
  doc.text('NUTRITION PER SERVING:', margin + 4, y + 5);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(50, 50, 50);
  const nutText = `Calories: ${recipe.nutrition.calories} kcal  |  Protein: ${recipe.nutrition.protein}  |  Carbs: ${recipe.nutrition.carbohydrates}  |  Fat: ${recipe.nutrition.fat}  |  Fiber: ${recipe.nutrition.fiber}`;
  doc.text(nutText, margin + 4, y + 11);
  y += 22;

  // Instructions
  checkPageOverflow(20);
  doc.setFillColor(244, 237, 228);
  doc.rect(margin, y, pageWidth - (margin * 2), 7, 'F');
  doc.setTextColor(44, 44, 44);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.text('STEP-BY-STEP COOKING INSTRUCTION', margin + 4, y + 5);
  y += 12;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  recipe.instructions.forEach(step => {
    const stepHeader = `Step ${step.stepNumber} ${step.estimatedMinutes ? '(' + step.estimatedMinutes + ' mins)' : ''}`;
    const lines = doc.splitTextToSize(`${stepHeader}: ${step.instruction}`, pageWidth - (margin * 2) - 8);
    checkPageOverflow((lines.length * 5) + 6);
    
    doc.setFont('helvetica', 'bold');
    doc.text(`Step ${step.stepNumber}: `, margin + 4, y);
    doc.setFont('helvetica', 'normal');
    const stepTextLines = doc.splitTextToSize(step.instruction, pageWidth - (margin * 2) - 20);
    doc.text(stepTextLines, margin + 22, y);
    y += (stepTextLines.length * 5) + 4;
  });

  // Footer on page
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text('Generated by Flavor Fusion AI – Smart AI Recipe Assistant', margin, pageHeight - 10);

  const fileName = recipe.title.toLowerCase().replace(/[^a-z0-9]+/g, '_') + '_recipe.pdf';
  doc.save(fileName);
}

export async function copyRecipeToClipboard(recipe: Recipe): Promise<boolean> {
  try {
    const text = generateRecipeText(recipe);
    await navigator.clipboard.writeText(text);
    return true;
  } catch (err) {
    console.error('Failed to copy recipe to clipboard:', err);
    return false;
  }
}
